In [1]:
from pathlib import Path
from utils import read_stats_pairs
from IPython.display import Markdown, display
def printmd(string):
    display(Markdown(string.replace('\n', '<br>')))

In [2]:
# global settings go here
test_run = True
dataset_name = 'AllPointCloudsAsCSVs_central'
method = 'delcech'
stat_dump_dir_name = '/scratch/chromatic'
num_workers = 48
# default settings when running locally
if test_run:
    stat_dump_dir_name = 'stat_dump'
    num_workers = min(num_workers, 8)
# cell_type_names_file = 'cell_type_labels.csv'
print("yes")

In [3]:
# First parse the dataset into a ParquetDataset object
# This does not actually read in the data
stat_dump_dir = Path(stat_dump_dir_name).joinpath(dataset_name)
dataset = read_stats_pairs(stat_dump_dir)

In [4]:
# Get the list of column headers of the dataset
print(str(dataset.schema))

codomain: list<element: string><br>  child 0, element: string<br>ker0_avg_birth: double<br>ker0_sd_birth: double<br>ker0_med_birth: double<br>ker0_iqr_birth: double<br>ker0_range_birth: double<br>ker0_p25_birth: double<br>ker0_p75_birth: double<br>ker0_p10_birth: double<br>ker0_p90_birth: double<br>ker0_avg_death: double<br>ker0_sd_death: double<br>ker0_med_death: double<br>ker0_iqr_death: double<br>ker0_range_death: double<br>ker0_p25_death: double<br>ker0_p75_death: double<br>ker0_p10_death: double<br>ker0_p90_death: double<br>ker0_avg_midpt: double<br>ker0_sd_midpt: double<br>ker0_med_midpt: double<br>ker0_iqr_midpt: double<br>ker0_range_midpt: double<br>ker0_p25_midpt: double<br>ker0_p75_midpt: double<br>ker0_p10_midpt: double<br>ker0_p90_midpt: double<br>ker0_avg_length: double<br>ker0_sd_length: double<br>ker0_med_length: double<br>ker0_iqr_length: double<br>ker0_range_length: double<br>ker0_p25_length: double<br>ker0_p75_length: double<br>ker0_p10_length: double<br>ker0_p90_length: double<br>ker0_num_bars: double<br>ker0_entropy: double<br>ker1_avg_birth: double<br>ker1_sd_birth: double<br>ker1_med_birth: double<br>ker1_iqr_birth: double<br>ker1_range_birth: double<br>ker1_p25_birth: double<br>ker1_p75_birth: double<br>ker1_p10_birth: double<br>ker1_p90_birth: double<br>ker1_avg_death: double<br>ker1_sd_death: double<br>ker1_med_death: double<br>ker1_iqr_death: double<br>ker1_range_death: double<br>ker1_p25_death: double<br>ker1_p75_death: double<br>ker1_p10_death: double<br>ker1_p90_death: double<br>ker1_avg_midpt: double<br>ker1_sd_midpt: double<br>ker1_med_midpt: double<br>ker1_iqr_midpt: double<br>ker1_range_midpt: double<br>ker1_p25_midpt: double<br>ker1_p75_midpt: double<br>ker1_p10_midpt: double<br>ker1_p90_midpt: double<br>ker1_avg_length: double<br>ker1_sd_length: double<br>ker1_med_length: double<br>ker1_iqr_length: double<br>ker1_range_length: double<br>ker1_p25_length: double<br>ker1_p75_length: double<br>ker1_p10_length: double<br>ker1_p90_length: double<br>ker1_num_bars: double<br>ker1_entropy: double<br>cok0_avg_birth: double<br>cok0_sd_birth: double<br>cok0_med_birth: double<br>cok0_iqr_birth: double<br>cok0_range_birth: double<br>cok0_p25_birth: double<br>cok0_p75_birth: double<br>cok0_p10_birth: double<br>cok0_p90_birth: double<br>cok0_avg_death: double<br>cok0_sd_death: double<br>cok0_med_death: double<br>cok0_iqr_death: double<br>cok0_range_death: double<br>cok0_p25_death: double<br>cok0_p75_death: double<br>cok0_p10_death: double<br>cok0_p90_death: double<br>cok0_avg_midpt: double<br>cok0_sd_midpt: double<br>cok0_med_midpt: double<br>cok0_iqr_midpt: double<br>cok0_range_midpt: double<br>cok0_p25_midpt: double<br>cok0_p75_midpt: double<br>cok0_p10_midpt: double<br>cok0_p90_midpt: double<br>cok0_avg_length: double<br>cok0_sd_length: double<br>cok0_med_length: double<br>cok0_iqr_length: double<br>cok0_range_length: double<br>cok0_p25_length: double<br>cok0_p75_length: double<br>cok0_p10_length: double<br>cok0_p90_length: double<br>cok0_num_bars: double<br>cok0_entropy: double<br>cok1_avg_birth: double<br>cok1_sd_birth: double<br>cok1_med_birth: double<br>cok1_iqr_birth: double<br>cok1_range_birth: double<br>cok1_p25_birth: double<br>cok1_p75_birth: double<br>cok1_p10_birth: double<br>cok1_p90_birth: double<br>cok1_avg_death: double<br>cok1_sd_death: double<br>cok1_med_death: double<br>cok1_iqr_death: double<br>cok1_range_death: double<br>cok1_p25_death: double<br>cok1_p75_death: double<br>cok1_p10_death: double<br>cok1_p90_death: double<br>cok1_avg_midpt: double<br>cok1_sd_midpt: double<br>cok1_med_midpt: double<br>cok1_iqr_midpt: double<br>cok1_range_midpt: double<br>cok1_p25_midpt: double<br>cok1_p75_midpt: double<br>cok1_p10_midpt: double<br>cok1_p90_midpt: double<br>cok1_avg_length: double<br>cok1_sd_length: double<br>cok1_med_length: double<br>cok1_iqr_length: double<br>cok1_range_length: double<br>cok1_p25_length: double<br>cok1_p75_length: double<br>cok1_p10_length: double<br>cok1_p90_length: double<br>cok1_num_bars: double<br>cok1_entropy: double<br>dom0_avg_birth: double<br>dom0_sd_birth: double<br>dom0_med_birth: double<br>dom0_iqr_birth: double<br>dom0_range_birth: double<br>dom0_p25_birth: double<br>dom0_p75_birth: double<br>dom0_p10_birth: double<br>dom0_p90_birth: double<br>dom0_avg_death: double<br>dom0_sd_death: double<br>dom0_med_death: double<br>dom0_iqr_death: double<br>dom0_range_death: double<br>dom0_p25_death: double<br>dom0_p75_death: double<br>dom0_p10_death: double<br>dom0_p90_death: double<br>dom0_avg_midpt: double<br>dom0_sd_midpt: double<br>dom0_med_midpt: double<br>dom0_iqr_midpt: double<br>dom0_range_midpt: double<br>dom0_p25_midpt: double<br>dom0_p75_midpt: double<br>dom0_p10_midpt: double<br>dom0_p90_midpt: double<br>dom0_avg_length: double<br>dom0_sd_length: double<br>dom0_med_length: double<br>dom0_iqr_length: double<br>dom0_range_length: double<br>dom0_p25_length: double<br>dom0_p75_length: double<br>dom0_p10_length: double<br>dom0_p90_length: double<br>dom0_num_bars: double<br>dom0_entropy: double<br>dom1_avg_birth: double<br>dom1_sd_birth: double<br>dom1_med_birth: double<br>dom1_iqr_birth: double<br>dom1_range_birth: double<br>dom1_p25_birth: double<br>dom1_p75_birth: double<br>dom1_p10_birth: double<br>dom1_p90_birth: double<br>dom1_avg_death: double<br>dom1_sd_death: double<br>dom1_med_death: double<br>dom1_iqr_death: double<br>dom1_range_death: double<br>dom1_p25_death: double<br>dom1_p75_death: double<br>dom1_p10_death: double<br>dom1_p90_death: double<br>dom1_avg_midpt: double<br>dom1_sd_midpt: double<br>dom1_med_midpt: double<br>dom1_iqr_midpt: double<br>dom1_range_midpt: double<br>dom1_p25_midpt: double<br>dom1_p75_midpt: double<br>dom1_p10_midpt: double<br>dom1_p90_midpt: double<br>dom1_avg_length: double<br>dom1_sd_length: double<br>dom1_med_length: double<br>dom1_iqr_length: double<br>dom1_range_length: double<br>dom1_p25_length: double<br>dom1_p75_length: double<br>dom1_p10_length: double<br>dom1_p90_length: double<br>dom1_num_bars: double<br>dom1_entropy: double<br>cod0_avg_birth: double<br>cod0_sd_birth: double<br>cod0_med_birth: double<br>cod0_iqr_birth: double<br>cod0_range_birth: double<br>cod0_p25_birth: double<br>cod0_p75_birth: double<br>cod0_p10_birth: double<br>cod0_p90_birth: double<br>cod0_avg_death: double<br>cod0_sd_death: double<br>cod0_med_death: double<br>cod0_iqr_death: double<br>cod0_range_death: double<br>cod0_p25_death: double<br>cod0_p75_death: double<br>cod0_p10_death: double<br>cod0_p90_death: double<br>cod0_avg_midpt: double<br>cod0_sd_midpt: double<br>cod0_med_midpt: double<br>cod0_iqr_midpt: double<br>cod0_range_midpt: double<br>cod0_p25_midpt: double<br>cod0_p75_midpt: double<br>cod0_p10_midpt: double<br>cod0_p90_midpt: double<br>cod0_avg_length: double<br>cod0_sd_length: double<br>cod0_med_length: double<br>cod0_iqr_length: double<br>cod0_range_length: double<br>cod0_p25_length: double<br>cod0_p75_length: double<br>cod0_p10_length: double<br>cod0_p90_length: double<br>cod0_num_bars: double<br>cod0_entropy: double<br>cod1_avg_birth: double<br>cod1_sd_birth: double<br>cod1_med_birth: double<br>cod1_iqr_birth: double<br>cod1_range_birth: double<br>cod1_p25_birth: double<br>cod1_p75_birth: double<br>cod1_p10_birth: double<br>cod1_p90_birth: double<br>cod1_avg_death: double<br>cod1_sd_death: double<br>cod1_med_death: double<br>cod1_iqr_death: double<br>cod1_range_death: double<br>cod1_p25_death: double<br>cod1_p75_death: double<br>cod1_p10_death: double<br>cod1_p90_death: double<br>cod1_avg_midpt: double<br>cod1_sd_midpt: double<br>cod1_med_midpt: double<br>cod1_iqr_midpt: double<br>cod1_range_midpt: double<br>cod1_p25_midpt: double<br>cod1_p75_midpt: double<br>cod1_p10_midpt: double<br>cod1_p90_midpt: double<br>cod1_avg_length: double<br>cod1_sd_length: double<br>cod1_med_length: double<br>cod1_iqr_length: double<br>cod1_range_length: double<br>cod1_p25_length: double<br>cod1_p75_length: double<br>cod1_p10_length: double<br>cod1_p90_length: double<br>cod1_num_bars: double<br>cod1_entropy: double<br>im0_avg_birth: double<br>im0_sd_birth: double<br>im0_med_birth: double<br>im0_iqr_birth: double<br>im0_range_birth: double<br>im0_p25_birth: double<br>im0_p75_birth: double<br>im0_p10_birth: double<br>im0_p90_birth: double<br>im0_avg_death: double<br>im0_sd_death: double<br>im0_med_death: double<br>im0_iqr_death: double<br>im0_range_death: double<br>im0_p25_death: double<br>im0_p75_death: double<br>im0_p10_death: double<br>im0_p90_death: double<br>im0_avg_midpt: double<br>im0_sd_midpt: double<br>im0_med_midpt: double<br>im0_iqr_midpt: double<br>im0_range_midpt: double<br>im0_p25_midpt: double<br>im0_p75_midpt: double<br>im0_p10_midpt: double<br>im0_p90_midpt: double<br>im0_avg_length: double<br>im0_sd_length: double<br>im0_med_length: double<br>im0_iqr_length: double<br>im0_range_length: double<br>im0_p25_length: double<br>im0_p75_length: double<br>im0_p10_length: double<br>im0_p90_length: double<br>im0_num_bars: double<br>im0_entropy: double<br>im1_avg_birth: double<br>im1_sd_birth: double<br>im1_med_birth: double<br>im1_iqr_birth: double<br>im1_range_birth: double<br>im1_p25_birth: double<br>im1_p75_birth: double<br>im1_p10_birth: double<br>im1_p90_birth: double<br>im1_avg_death: double<br>im1_sd_death: double<br>im1_med_death: double<br>im1_iqr_death: double<br>im1_range_death: double<br>im1_p25_death: double<br>im1_p75_death: double<br>im1_p10_death: double<br>im1_p90_death: double<br>im1_avg_midpt: double<br>im1_sd_midpt: double<br>im1_med_midpt: double<br>im1_iqr_midpt: double<br>im1_range_midpt: double<br>im1_p25_midpt: double<br>im1_p75_midpt: double<br>im1_p10_midpt: double<br>im1_p90_midpt: double<br>im1_avg_length: double<br>im1_sd_length: double<br>im1_med_length: double<br>im1_iqr_length: double<br>im1_range_length: double<br>im1_p25_length: double<br>im1_p75_length: double<br>im1_p10_length: double<br>im1_p90_length: double<br>im1_num_bars: double<br>im1_entropy: double<br>rel0_avg_birth: double<br>rel0_sd_birth: double<br>rel0_med_birth: double<br>rel0_iqr_birth: double<br>rel0_range_birth: double<br>rel0_p25_birth: double<br>rel0_p75_birth: double<br>rel0_p10_birth: double<br>rel0_p90_birth: double<br>rel0_avg_death: double<br>rel0_sd_death: double<br>rel0_med_death: double<br>rel0_iqr_death: double<br>rel0_range_death: double<br>rel0_p25_death: double<br>rel0_p75_death: double<br>rel0_p10_death: double<br>rel0_p90_death: double<br>rel0_avg_midpt: double<br>rel0_sd_midpt: double<br>rel0_med_midpt: double<br>rel0_iqr_midpt: double<br>rel0_range_midpt: double<br>rel0_p25_midpt: double<br>rel0_p75_midpt: double<br>rel0_p10_midpt: double<br>rel0_p90_midpt: double<br>rel0_avg_length: double<br>rel0_sd_length: double<br>rel0_med_length: double<br>rel0_iqr_length: double<br>rel0_range_length: double<br>rel0_p25_length: double<br>rel0_p75_length: double<br>rel0_p10_length: double<br>rel0_p90_length: double<br>rel0_num_bars: double<br>rel0_entropy: double<br>rel1_avg_birth: double<br>rel1_sd_birth: double<br>rel1_med_birth: double<br>rel1_iqr_birth: double<br>rel1_range_birth: double<br>rel1_p25_birth: double<br>rel1_p75_birth: double<br>rel1_p10_birth: double<br>rel1_p90_birth: double<br>rel1_avg_death: double<br>rel1_sd_death: double<br>rel1_med_death: double<br>rel1_iqr_death: double<br>rel1_range_death: double<br>rel1_p25_death: double<br>rel1_p75_death: double<br>rel1_p10_death: double<br>rel1_p90_death: double<br>rel1_avg_midpt: double<br>rel1_sd_midpt: double<br>rel1_med_midpt: double<br>rel1_iqr_midpt: double<br>rel1_range_midpt: double<br>rel1_p25_midpt: double<br>rel1_p75_midpt: double<br>rel1_p10_midpt: double<br>rel1_p90_midpt: double<br>rel1_avg_length: double<br>rel1_sd_length: double<br>rel1_med_length: double<br>rel1_iqr_length: double<br>rel1_range_length: double<br>rel1_p25_length: double<br>rel1_p75_length: double<br>rel1_p10_length: double<br>rel1_p90_length: double<br>rel1_num_bars: double<br>rel1_entropy: double<br>method: dictionary<values=string, indices=int32, ordered=0><br>patient_id: dictionary<values=int32, indices=int32, ordered=0><br>sample_type: dictionary<values=string, indices=int32, ordered=0><br>sample_id: dictionary<values=int32, indices=int32, ordered=0><br>-- schema metadata --<br>pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 0, "' + 59914

In [5]:
# Create a table with just the list of patients
patients = dataset.read(columns=['patient_id']).to_pandas().drop_duplicates()
patients.head()

      patient_id
0          10171
8511       11818
25426      12575
37369      13158
49189      13309

In [10]:
# Read in all rows of the dataset corresponding to the first patient
first_patient_id = patients['patient_id'][0]
first_patient_all_data = read_stats_pairs(stat_dump_dir, filters=
                                          [('patient_id', '=', first_patient_id)]
                                         ).read().to_pandas()
display(first_patient_all_data)

,codomain,ker0_avg_birth,ker0_sd_birth,ker0_med_birth,ker0_iqr_birth,ker0_range_birth,ker0_p25_birth,ker0_p75_birth,ker0_p10_birth,ker0_p90_birth,...,rel1_p25_length,rel1_p75_length,rel1_p10_length,rel1_p90_length,rel1_num_bars,rel1_entropy,method,patient_id,sample_type,sample_id
0,"[CD146, CD34]",42.331427,43.136704,38.937785,41.253011,153.000817,9.814689,51.067700,0.000000,110.898158,...,2.044143,33.173051,1.093558,64.296495,31.0,2.626453,delcech,10171,adenoma,101
1,"[CD146, Epithelium (imm)]",15.181529,6.654967,12.711169,7.951219,24.610739,10.913495,18.864714,8.749065,24.672230,...,0.206817,13.988421,0.040468,38.910545,73.0,3.076690,delcech,10171,adenoma,101
2,"[CD146, Neutrophil]",22.908412,22.320654,14.720728,17.055356,98.794735,9.517388,26.572744,4.924953,46.225869,...,0.796355,14.162160,0.061155,42.567263,68.0,3.003263,delcech,10171,adenoma,101
3,"[CD146, Cytotoxic T Cell]",7.160670,5.015969,6.256722,4.442506,36.854318,4.343401,8.785907,3.096186,10.393334,...,0.267234,6.827135,0.037042,22.885709,119.0,3.347128,delcech,10171,adenoma,101
4,"[CD146, SMA]",13.087191,35.888955,0.000000,0.000000,150.134939,0.000000,0.000000,0.000000,40.231719,...,15.469296,63.835165,7.227664,155.949188,20.0,2.458357,delcech,10171,adenoma,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8506,"[Cytotoxic T Cell, T Helper Cell]",1.508143,3.716258,0.000000,0.000000,20.353132,0.000000,0.000000,0.000000,7.289008,...,4.511039,10.358798,0.684923,13.844162,169.0,4.745757,delcech,10171,cancer,90
8507,"[Periostin, T Helper Cell]",7.295168,6.135119,6.384083,4.439187,53.587755,4.189229,8.628416,3.022409,12.278377,...,0.204659,5.806312,0.023566,14.078366,192.0,4.287257,delcech,10171,cancer,90
8508,"[Epithelium (str), Macrophage]",6.781318,5.137036,6.047470,3.724843,53.178266,4.188286,7.913129,3.174016,11.013196,...,0.250226,4.755876,0.069137,9.263652,325.0,4.904929,delcech,10171,cancer,90
8509,"[Macrophage, T Helper Cell]",0.649323,3.716534,0.000000,0.000000,50.931326,0.000000,0.000000,0.000000,0.000000,...,5.135616,9.891172,0.942790,13.345913,277.0,5.336585,delcech,10171,cancer,90
8510,"[Epithelium (str), T Helper Cell]",6.273390,4.627158,5.712767,3.735724,53.178266,3.927842,7.663565,2.758571,10.119818,...,0.289673,5.067081,0.055720,9.676185,362.0,5.115959,delcech,10171,cancer,90

In [6]:
# For more complex comparisons, convert entirely to pandas first and then filter
# Warning: this loads the entire dataset into memory
df = dataset.read().to_pandas()
df.head()

ArrowNotImplementedError: Function 'equal' has no kernel matching input types (list<element: string>, list<item: string>)